In [8]:
import numpy as np
import torch
import torch
from torch.utils.data import TensorDataset,DataLoader

input = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

target = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

initial_target=np.array([[100],
[100],
[80],
[90],
[100]], dtype='float32')

weight = np.array([[10],
[20],
[15],
[11],
[30]], dtype='float32')

bias = np.array([[7],[7],[7],[7],[7]],dtype='float32')

prediction = (initial_target*weight) + bias
print(prediction)

[[1007.]
 [2007.]
 [1207.]
 [ 997.]
 [3007.]]


In [58]:
inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)
print(inputs)
print(targets)
dataset = TensorDataset(inputs,targets)
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)
weights= torch.randn(1,3, requires_grad=True)
bs = torch.randn(1, requires_grad=True)
print(weights)
print(bs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
tensor([[-1.5109, -0.6964,  0.2457]], requires_grad=True)
tensor([0.8181], requires_grad=True)


In [59]:
def model(X):
  return X @ weights.t() + bs

for x,y in train_loader:
    preds = model(x)
    print("Prediction :\n",preds)
    print("\nActual Value:\n",y)
    break

def mse_loss(predictions, targets):
  difference = predictions - targets
  return torch.sum(difference * difference)/ difference.numel() 
for x,y in train_loader:
  preds=model(x)
  print("Prediction :\n", preds)
  print("\nActual Value:\n",y)
  print("\nLoss : ",mse_loss(preds,y))
  break

Prediction :
 tensor([[-145.5705],
        [-182.2316],
        [-174.1467],
        [-153.0894]], grad_fn=<AddBackward0>)

Actual Value:
 tensor([[ 56.],
        [ 81.],
        [ 22.],
        [103.]])
Prediction :
 tensor([[-182.2316],
        [-209.6958],
        [-174.1467],
        [-145.5705]], grad_fn=<AddBackward0>)

Actual Value:
 tensor([[ 81.],
        [119.],
        [ 22.],
        [ 56.]])

Loss :  tensor(64109.0078, grad_fn=<DivBackward0>)


In [55]:
epochs = 100
for i in range(epochs):
    for x,y in train_loader:
        preds = model(x)
        loss = mse_loss(preds, y)
        loss.backward()
        with torch.no_grad():
            weights -= weights.grad *1e-5
            bs -= bs.grad * 1e-5
            weights.grad.zero_()
            bs.grad.zero_()

for x,y in train_loader:
  preds= model(x)
  print("\Prediction :\n",preds)
  print("\nActual value:\n",y)
  break

\Prediction :
 tensor([[102.8818],
        [118.7187],
        [ 21.4160],
        [ 57.6037]], grad_fn=<AddBackward0>)

Actual value:
 tensor([[103.],
        [119.],
        [ 22.],
        [ 56.]])


In [57]:
print(weights)
print(bs)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(inputs, targets)
test_input = np.array([[70, 34, 45]])
y_pred = model.predict(test_input)
print("Prediction: ", y_pred)
MSE = mse_loss(preds,y)
print("MSE: ",MSE)
print("Weights: ",weights)
print("Bias: ",bs)

tensor([[-0.4070,  0.8364,  0.7183]], requires_grad=True)
tensor([0.3918], requires_grad=True)
Prediction:  [[31.47395247]]
MSE:  tensor(0.7515, grad_fn=<DivBackward0>)
Weights:  tensor([[-0.4070,  0.8364,  0.7183]], requires_grad=True)
Bias:  tensor([0.3918], requires_grad=True)


In [26]:
def mse_loss(predictions, targets):
  difference = predictions - targets
  return torch.sum(difference * difference)/ difference.numel()
for x,y in train_loader:
  preds=model(x)
  print("Prediction is :\n", preds)
  print("\nActual targets is :\n",y)
  print("\nLoss is: ",mse_loss(preds,y))
  break

epochs = 1000
for i in range(epochs):
    for x,y in train_loader:
        preds = model(x)
        loss = mse_loss(preds, y)
        loss.backward()
        with torch.no_grad():
            weights -= weights.grad *0.1
            bs -= bs.grad * 0.1
            weights.grad.zero_()
            bs.grad.zero_()

for x,y in train_loader:
  preds= model(x)
  print("\nFinal Prediction is :\n",preds)
  print("\nActual targets are :\n",y)
  break
MSE = mse_loss(preds,y)
print("MSE: ",MSE)

print("Weights: ",weights)
print("Bias: ",bs)

Prediction is :
 tensor([[nan],
        [nan],
        [nan],
        [nan]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 81.],
        [103.],
        [119.],
        [ 56.]])

Loss is:  tensor(nan, grad_fn=<DivBackward0>)

Final Prediction is :
 tensor([[nan],
        [nan],
        [nan],
        [nan]], grad_fn=<AddBackward0>)

Actual targets are :
 tensor([[ 22.],
        [103.],
        [119.],
        [ 56.]])
MSE:  tensor(nan, grad_fn=<DivBackward0>)
Weights:  tensor([[nan, nan, nan]], requires_grad=True)
Bias:  tensor([nan], requires_grad=True)


In [36]:
import torch
from torch.utils.data import TensorDataset,DataLoader
from sklearn.model_selection import train_test_split
input = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

target = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

initial_target=np.array([[100],
[100],
[80],
[90],
[100]], dtype='float32')

weight = np.array([[10],
[20],
[15],
[11],
[30]], dtype='float32')

bias = np.array([[7],[7],[7],[7],[7]],dtype='float32')
prediction = (initial_target*weight) + bias
loss_arr=[];
inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)
X_train, X_val, y_train, y_val = train_test_split(inputs, targets, random_state=35)
dataset = TensorDataset(inputs,targets)
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)
weights= torch.randn(1,3, requires_grad=True)
bs = torch.randn(1, requires_grad=True)
print(weights)
print(bs)

def model(X):
  return X @ weights.t() + bs 
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

def mse_loss(predictions, targets):
  difference = predictions - targets
  return torch.sum(difference * difference)/ difference.numel() 

for x,y in train_loader:
  preds=model(x)
  print("Prediction is :\n", preds)
  print("\nActual targets is :\n",y)
  print("\nLoss is: ",mse_loss(preds,y))
  break
epochs = 100
for i in range(epochs):
    for x,y in train_loader:
        preds = model(x)
        loss = mse_loss(preds, y)
        loss_arr+=loss
        loss.backward()
        with torch.no_grad():
            weights -= weights.grad *1e-7
            bs -= bs.grad * 1e-7
            weights.grad.zero_()
            bs.grad.zero_()

for x,y in train_loader:
  preds= model(x)
  print("\nFinal Prediction is :\n",preds)
  print("\nActual targets are :\n",y)
  break

tensor([[1.1219, 0.5023, 0.1569]], requires_grad=True)
tensor([1.0111], requires_grad=True)
Prediction is :
 tensor([[157.3465],
        [175.0217],
        [142.8495],
        [137.6237]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 81.],
        [119.],
        [ 22.],
        [103.]])
Prediction is :
 tensor([[137.6237],
        [123.3096],
        [175.0217],
        [157.3465]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[103.],
        [ 56.],
        [119.],
        [ 81.]])

Loss is:  tensor(3674.1479, grad_fn=<DivBackward0>)


TypeError: ignored

In [35]:
MSE = mse_loss(preds,y)
print("MSE: ",MSE)
print("Weights: ",weights)
print("Bias: ",bs)

MSE:  tensor(48969.5078, grad_fn=<DivBackward0>)
Weights:  tensor([[-1.3500, -0.5612,  0.3562]], requires_grad=True)
Bias:  tensor([-0.0834], requires_grad=True)
