In [2]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)

temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))
Predicted Value: [1]
Predicted Value: [1]
Predicted Value: [1]


In [3]:
#Import scikit-learn dataset library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)
# print data(feature)shape
print("\nData shape: ",iris.data.shape)
#print data(target)shape
print("\nTraget shape: ",iris.target.shape)
#print("\nData: ",iris.data)
#print("\nTarget: ",iris.target)
print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Traget shape:  (150,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (100, 4)

New Traget shape:  (100,)


In [15]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget, test_size = 0.20, random_state = 35)
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
Accuracy: 0.9
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

Accuracy: 0.95


array([[10,  1],
       [ 0,  9]])

In [16]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 1.0
recall: 0.9090909090909091


In [6]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from google.colab import drive
# take input dataset from drive
drive.mount('/content/drive')
data = pd.read_csv('/content/drive/MyDrive/sem6 myfolder/mldatasets/Dataset1.csv')
print(data)

x = data.iloc[:,:-1].values
le = LabelEncoder()
x[:,0] = le.fit_transform(x[:,0])
x[:,1] = le.fit_transform(x[:,1])
x[:,2] = le.fit_transform(x[:,2])
x[:,3] = le.fit_transform(x[:,3])
print(x)

y = data.iloc[:,-1].values
y = le.fit_transform(y)
print(y)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N
[[1 1 2 0]
 [1 1 0 1]
 [0 1 2 0]
 [2 2 2 0]
 [2 0 2 0]
 [2 0 1 1]
 [0 0 2 1]
 [1 2 2 0]
 [1 0 1 0]
 [2 2 0 0]
 [1 2 0 1]
 [0 2 1 1]
 [0 1 2 0]
 [2 2 2 1]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [18]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics

# using random state as last 2 digits of my permanent ID
data_train, data_test, target_train, target_test = train_test_split(x,y,train_size=0.9,test_size=0.1, random_state=88)
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))
# Accuracy:  0.5
target_pred = gnb.predict([[1,2,2,0],[2,0,0,1]])
print(target_pred)

Accuracy:  0.5
[1 0]


In [19]:
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
print('precision: {}'.format(precision))
recall = recall_score(target_test, target_pred)
print('recall: {}'.format(recall))
predicted = gnb.predict([[1,2,0,1]])
prob = gnb.predict_proba([[1,2,0,1]])
predicted,prob

precision: 0.0
recall: 0.0


(array([0]), array([[0.50143637, 0.49856363]]))

In [9]:
# Getting breast cancer dataset
data=datasets.load_breast_cancer()
data.target
data.keys()
dt, data_test, tr, tt = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 0)
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(dt, tr)
target_pred = gnb.predict(data_test)
accuracy = metrics.accuracy_score(tt, target_pred)
precision = metrics.precision_score(tt, target_pred, average=None)
recall = metrics.recall_score(tt, target_pred, average=None)
print('Accuracy: {}'.format(accuracy))


Accuracy: 0.9666666666666667


In [12]:
print('recall: {}'.format(recall))
print('precision: {}'.format(precision))
target_pred = gnb.predict([[1,2,2,0],[2,0,0,1]])
print(target_pred)

recall: [1.         1.         0.83333333]
precision: [1.         0.92857143 1.        ]
[0 1]
