In [16]:
import numpy as np
import torch
import random

inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70]], dtype='float32')

targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')
print(inputs)
print(targets)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]
 [ 73.  67.  43.]
 [ 91.  88.  64.]]
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]]


In [17]:
tensor_inputs = torch.from_numpy(inputs)
tensor_targets = torch.from_numpy(targets)
print(tensor_inputs)
print(tensor_targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])


In [11]:
weight = torch.randn(1,3)
biases = torch.randn(1,1)
print(weight)
print(biases)

tensor([[1.6030, 1.6859, 1.0152]])
tensor([[-0.3573]])


In [ ]:
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as fn
dataset= TensorDataset(inputs,targets)
dataset[0]
dataloader = DataLoader(dataset,batch_size=15, shuffle=True)
model = nn.Linear(in_features=3, out_features=2, bias=True)
optimizer = torch.optim.SGD(model.parameters(), 0.0001)
loss_fn = fn.mse_loss

In [ ]:
def fit(num_epochs:int, model, loss_fn, optimizer):
  for epoch in range(num_epochs):
    batch = 0
    for xb,yb in dataloader:
      batch += 1
      pred = model(xb)
      loss = loss_fn(pred, yb)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print('epoch {} batch {} batch size {} loss {}'.format(epoch,batch,len(xb),loss.item()))

fit(1000, model,loss_fn, optimizer)
data = torch.Tensor([[87, 134, 58], [102, 43, 37], [69, 96,70]])
targets = torch.Tensor([[119, 133], [22, 37], [103, 119]])
pre_data = model(data)
print("Predict (after training): ",targets,"\n", pre_data)